apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: yourmail@scaleway.com
    #server: https://acme-staging-v02.api.letsencrypt.org/directory # Comment this line for production purposes
    server: https://acme-v02.api.letsencrypt.org/directory # Comment this line testing purposes
    privateKeySecretRef:
      name: acme-account-key
    solvers:
    - http01:
        ingress:
          class: traefik
