apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- redis-deployment.yaml
- redis-pvc.yaml
- redis-service.yaml
- stack-blob-pvc.yaml
- stack-deployment.yaml
- stack-service.yaml

# namespace to deploy all Resources to
namespace: lorawan-stack

# labels added to all Resources
commonLabels:
  release: testing

configMapGenerator:
- name: ttn-lw-stack-config
  files:
    - ttn-lw-stack-docker.yaml

images:
  - name: redis
    newName: redis
    newTag: "6.2-rc"
  - name: ttn-stack
    newName: thethingsnetwork/lorawan-stack
    newTag: "3.10"
