apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Add this is you want to expose the admin dashboard of traefik
# - traefik/ingress.yaml
resources:
- cert-issuer.yaml
- traefik/rbac.yaml
- traefik/crd.yaml
- traefik/configmap.yaml
- traefik/deployment.yaml
- traefik/service.yaml
- traefik/service_dashboard.yaml
- redis/deployment.yaml
- redis/pvc.yaml
- redis/service.yaml
- stack/pvc.yaml
- stack/deployment.yaml
- stack/service.yaml
- stack/ingress.yaml
- grafana/deployment.yaml
- grafana/pvc.yaml
- grafana/service.yaml
- grafana/ingress.yaml

# namespace to deploy all Resources to
namespace: lorawan-stack

# labels added to all Resources
commonLabels:
  release: testing

configMapGenerator:
- name: ttn-lw-stack-config
  files:
    - ttn-lw-stack-docker.yaml

images:
  - name: redis
    newName: redis
    newTag: "6.2-rc"
  - name: grafana
    newName: grafana/grafana
    newTag: "7.3.6"
  - name: ttn-stack
    newName: thethingsnetwork/lorawan-stack
    newTag: "3.10"
