# Identity Server configuration
# Email configuration for "thethings.example.com"
is:
  email:
    sender-name: 'The Things Stack'
    sender-address: 'noreply@thethings.example.com'
    network:
      name: 'The Things Stack'
      console-url: 'https://134.197.75.58:30126/console'
      identity-server-url: 'https://134.197.75.58:30126/oauth'

    # If sending email with Sendgrid
    # provider: sendgrid
    # sendgrid:
    #   api-key: '...'              # enter Sendgrid API key

    # If sending email with SMTP
    # provider: smtp
    # smtp:
    #   address:  '...'             # enter SMTP server address
    #   username: '...'             # enter SMTP server username
    #   password: '...'             # enter SMTP server password

  # Web UI configuration for "thethings.example.com":
  oauth:
    ui:
      canonical-url: 'https://134.197.75.58:30126/oauth'
      is:
        base-url: 'https://134.197.75.58:30126/api/v3'

# HTTP server configuration
#http:
#  cookie:
#    block-key: ''                # generate 32 bytes (openssl rand -hex 32)
#    hash-key: ''                 # generate 64 bytes (openssl rand -hex 64)
#  metrics:
#    password: 'metrics'               # choose a password
#  pprof:
#    password: 'pprof'                 # choose a password

# If using custom certificates:
tls:
  source: file
  root-ca: /var/lib/certificates/ca.crt
  certificate: /var/lib/certificates/tls.crt
  key: /var/lib/certificates/tls.key

# If Gateway Server enabled, defaults for "thethings.example.com":
gs:
  mqtt:
    public-address: 'thethings.example.com:1882'
    public-tls-address: 'thethings.example.com:8882'
  mqtt-v2:
    public-address: 'thethings.example.com:1881'
    public-tls-address: 'thethings.example.com:8881'

# If Gateway Configuration Server enabled, defaults for "thethings.example.com":
gcs:
  basic-station:
    default:
      lns-uri: 'wss://thethings.example.com:8887'
  the-things-gateway:
    default:
      mqtt-server: 'mqtts://thethings.example.com:8881'

# Web UI configuration for "thethings.example.com":
console:
  ui:
    canonical-url: 'https://134.197.75.58:30126/console'
    is:
      base-url: 'https://134.197.75.58:30126/api/v3'
    gs:
      base-url: 'https://134.197.75.58:30126/api/v3'
    ns:
      base-url: 'https://134.197.75.58:30126/api/v3'
    as:
      base-url: 'https://134.197.75.58:30126/api/v3'
    js:
      base-url: 'https://134.197.75.58:30126/api/v3'
    qrg:
      base-url: 'https://134.197.75.58:30126/api/v3'
    edtc:
      base-url: 'https://134.197.75.58:30126/api/v3'

  oauth:
    authorize-url: 'https://134.197.75.58:30126/oauth/authorize'
    token-url: 'https://134.197.75.58:30126/oauth/token'
    logout-url: 'https://134.197.75.58:30126/oauth/logout'
    client-id: 'console'
    client-secret: 'console'          # choose or generate a secret

# If Application Server enabled, defaults for "thethings.example.com":
as:
  mqtt:
    public-address: 'https://134.197.75.58:1883'
    public-tls-address: 'https://134.197.75.58:8883'
  webhooks:
    downlink:
      public-address: 'thethings.example.com:1885/api/v3'

# If Device Claiming Server enabled, defaults for "thethings.example.com":
dcs:
  oauth:
    authorize-url: 'https://134.197.75.58:30126/oauth/authorize'
    token-url: 'https://134.197.75.58:30126/oauth/token'
    logout-url: 'https://134.197.75.58:30126/oauth/logout'
    client-id: 'device-claiming'
    client-secret: 'device-claiming'          # choose or generate a secret
  ui:
    canonical-url: 'https://134.197.75.58:30126/claim'
    as:
      base-url: 'https://134.197.75.58:30126/api/v3'
    dcs:
      base-url: 'https://134.197.75.58:30126/api/v3'
    is:
      base-url: 'https://134.197.75.58:30126/api/v3'
    ns:
      base-url: 'https://134.197.75.58:30126/api/v3'
