apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stack-blob
  namespace: thingstack
spec:
  storageClassName: "rook-ceph-block"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
