apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: redis
  name: redis
  namespace: thingstack
spec:
  storageClassName: "rook-ceph-block"
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
